from __future__ import annotations

from typing import Protocol


class Storage(Protocol):
    def exists(self, key: str) -> bool: ...

    def get_url(self, key: str, expires_sec: int = 3600) -> str: ...

    def put_file(self, key: str, src_path: str) -> None: ...

    def list(self, prefix: str = "") -> list[str]: ...

    def delete(self, key: str) -> None: ...
